# Generated by Django 4.0 on 2024-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
